### ISSUE TITLE
error on looking up onion hidden services

### ISSUE THREAD

**Issue by FraMecca** [brechtsanders/proxysocket#1]
If I look up .onion hidden services the test logs:

ERR: Error looking up host: ld74fqvoxpu5yi73.onion
Error looking up host: ld74fqvoxpu5yi73.onion

I believe it is an error on gethostbyname that is not routed through the socks server, resulting in a dns leak

**Comment by brechtsanders** [comment]
Hi,

You are correct about the DNS lookups not being done in the proxy server 
side.

I assume .onion is something related to tor networks?

Do you need the feature/option of server side lookups?

Out of curiosity: are you writing a program that will be using this library?

Regards

     Brecht

**Comment by FraMecca** [comment]
Hi!

I am currently writing a chat software using TOR hidden services and I would benefit from an option to do the lookup internally so that .onion domain could be used.

My [program](https://github.com/FraMecca/torchat) currently uses some boilerplate code to connect to the socks proxy and I would benefit from your library.

Best,
Francesco

**Comment by brechtsanders** [comment]
Hello,

I just wanted to let you know that I'm adding the possibility to choose 
proxy server side host lookups.

When I'm done, can I ask you to test this?

Regards

     Brecht

**Comment by brechtsanders** [comment]
Hi Francesco,

I just released version 0.1.3 
<https://github.com/brechtsanders/proxysocket/releases/tag/0.1.3>, which 
has the new function proxysocketconfig_use_proxy_dns() that adds the 
feature you requested.

Can you check if it works for what you are trying to do?

Looking forward to your feedback,

Brecht

**Comment by FraMecca** [comment]
Hi Brecht.
I am currently testing your library on my chat program.
Till now I haven't had any issue.
Thank you a lot for your time.

Best,
Francesco

**Comment by brechtsanders** [comment]
Hi Francesco,

I'm glad to hear that!

Regards

     Brecht

**Comment by GallaFrancesco** [comment]
Hi Brecht, 
I just want to say that I'm working with your library and I needed name resolution too.
Thanks for the fix!
Francesco

**Comment by brechtsanders** [comment]
Excellent!
