### ISSUE TITLE
Can I use it in Linux?

### ISSUE THREAD

**Issue by anson2416** [brechtsanders/proxysocket#2]
Hi Brecht,

My backend supports Socks4 only. I want to use your source which support Socks5. May I know if the code is workable in Linux box? Thanks.

**Comment by brechtsanders** [comment]
It was written to be cross platform, so it should work on Linux.
Have you tried it?

**Comment by brechtsanders** [comment]
In fact there is CI testing using Github Actions in place to build for Windows+macOS+Linux, see: https://github.com/brechtsanders/proxysocket/actions/workflows/proxysocket.yml
